stages:
  - build
  - deploy

build_branches:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/docker/production/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH
  only:
    - branches
  tags:
    - arm64

deploy_master:
  stage: deploy
  image: kroniak/ssh-client
  environment:
    name: master
    # url: https://exampleurl to be displayed in deploys
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - scp -P "$SSH_PORT" docker/production/docker-compose.yaml $SSH_DEPLOY_HOST:~/app/docker-compose.yaml
    - scp -P "$SSH_PORT" docker/production/deploy.sh $SSH_DEPLOY_HOST:~/app/deploy.sh
    - ssh -p "$SSH_PORT" $SSH_DEPLOY_HOST 'cd ~/app && ./deploy.sh'
  only:
    - master
